import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderPage from "./components/header";
import FooterPage from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  themeColor: "#d62860",
  width: "device-width",
  initialScale: 1,
};

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.calgirlanjali.in";

export const metadata: Metadata = {
  title: {
    default: "Anjali Escort Service | Premium Escorts in Pune & PCMC",
    template: "%s | Anjali Escort Service",
  },
  description: "Anjali Escort Service provides professional, elegant, and discreet escort services in Pune. Explore verified call girls, VIP models, and contact us 24/7.",
  authors: [{ name: "Anjali Escort Service" }],
  keywords: [
    // Top Pune Core Keywords
    "call girl",
    "cal girl",
    "call girl Pune",
    "call girls in Pune",
    "Pune call girl service",
    "Pune call girls",
    "escort service",
    "escort service in Pune",
    "Pune escort services",
    "Pune escort service",
    "Pune escorts",
    "escorts in Pune",
    "Anjali escort service",
    "calgirlanjali",
    "call girl Anjali",
    "independent escorts Pune",
    "independent call girl Pune",
    "VIP escorts Pune",
    "Russian escorts in Pune",
    "college girl escorts Pune",
    "housewife escorts Pune",
    "celebrity escorts Pune",
    "air hostess escorts Pune",
    "model escorts Pune",

    // Transit & Bus Stands & Railway Stations
    "pune bus stand escort service",
    "pune bus stand call girl",
    "pune bus stand escorts",
    "pune railway station escort",
    "pune railway station call girl",
    "pune railway station escort service",
    "call girl near pune station",
    "escort service near pune railway station",
    "pune st stand call girl",
    "swargate bus stand escort service",
    "swargate bus stand call girl",
    "swargate escort service",
    "swargate call girl",
    "swargate escorts",
    "shivajinagar bus stand call girl",
    "shivajinagar st stand escort service",
    "pune airport escort service",
    "pune airport call girl",
    "pune airport escorts",

    // PCMC Industrial & Suburbs
    "pcmc escort",
    "pcmc escorts",
    "pcmc escort service",
    "pcmc call girl",
    "pcmc call girl service",
    "call girls in pcmc",
    "Pimpri Chinchwad escorts",
    "Pimpri Chinchwad escort service",
    "Pimpri Chinchwad call girl",
    "call girls in Pimpri Chinchwad",
    "Pimpri call girl",
    "Pimpri escort service",
    "Pimpri escorts",
    "Chinchwad call girl",
    "Chinchwad escort service",
    "Chinchwad escorts",
    "Nigdi call girl",
    "Nigdi escort service",
    "Nigdi escorts",
    "Bhosari call girl",
    "Bhosari escorts",
    "Bhosari MIDC escort service",
    "Akurdi call girl",
    "Akurdi escort service",
    "Akurdi escorts",
    "Pimple Saudagar call girl",
    "Pimple Saudagar escort service",
    "Pimple Saudagar escorts",
    "Pimple Nilakh call girl",
    "Pimple Nilakh escort service",
    "Pimple Gurav call girl",
    "Ravet call girl",
    "Ravet escort service",
    "Tathawade call girl",
    "Tathawade escorts",
    "Moshi call girl",
    "Moshi escort service",
    "Chakan call girl",
    "Chakan MIDC escort service",
    "Chakan escorts",
    "Talegaon call girl",
    "Talegaon escort service",

    // Hinjewadi IT Park Corridor
    "Hinjewadi call girl",
    "call girls in Hinjewadi",
    "Hinjewadi escort service",
    "Hinjewadi escorts",
    "Hinjewadi IT park escorts",
    "Hinjewadi Phase 1 call girl",
    "Hinjewadi Phase 1 escorts",
    "Hinjewadi Phase 2 call girl",
    "Hinjewadi Phase 2 escorts",
    "Hinjewadi Phase 3 call girl",
    "Hinjewadi Phase 3 escort service",
    "Wakad call girl",
    "Wakad escort service",
    "Wakad escorts",
    "call girls in Wakad",
    "Bhumkar Chowk call girl",
    "Dange Chowk call girl",
    "Dange Chowk escort service",
    "Punawale call girl",
    "Punawale escort service",
    "Marunji call girl",

    // Koregaon Park & East Pune
    "Koregaon Park call girl",
    "call girls in Koregaon Park",
    "escort service Koregaon Park",
    "Koregaon Park escorts",
    "North Main Road call girl",
    "South Main Road escorts",
    "Kalyani Nagar call girl",
    "Kalyani Nagar escorts",
    "Kalyani Nagar escort service",
    "call girls in Kalyani Nagar",
    "Viman Nagar call girls",
    "Viman Nagar escorts",
    "Viman Nagar escort service",
    "Phoenix mall call girl Pune",
    "Kharadi call girl",
    "Kharadi escorts",
    "Kharadi escort service",
    "EON IT park call girl",
    "WTC Kharadi escort service",
    "Magarpatta call girl",
    "Magarpatta escorts",
    "Magarpatta escort service",
    "Magarpatta City escorts",
    "Cybercity call girl Pune",
    "Hadapsar call girls",
    "Hadapsar call girl",
    "Hadapsar escort service",
    "Hadapsar escorts",
    "SP Infocity call girl",
    "Wagholi call girl",
    "Wagholi escorts",
    "Wagholi escort service",
    "Nagar Road call girl",
    "Yerwada call girl",
    "Yerwada escorts",
    "Yerwada escort service",
    "Airport Road call girl",
    "Mundhwa call girl",
    "Mundhwa escorts",
    "Keshav Nagar call girl",
    "Tingre Nagar call girl",
    "Dhanori call girl",
    "Vishrantwadi call girl",
    "Vishrantwadi escorts",
    "Lohegaon call girl",

    // West Pune & Baner Corridor
    "Baner call girl",
    "call girls in Baner",
    "Baner escorts service",
    "Baner escorts",
    "Baner High Street call girl",
    "Baner High Street escorts",
    "Balewadi call girl",
    "Balewadi escorts",
    "Balewadi escort service",
    "Balewadi High Street escorts",
    "Mahalunge call girl",
    "Aundh call girl",
    "Aundh escorts",
    "Aundh escort service",
    "Bremen Chowk call girl",
    "Westend mall call girl",
    "Pashan call girl",
    "Pashan escorts",
    "Pashan escort service",
    "Sus Road call girl",
    "Bavdhan call girl",
    "Bavdhan escorts",
    "Bavdhan escort service",
    "Chandani Chowk call girl",
    "Chandani Chowk escorts",

    // Central & South Pune
    "Shivaji Nagar escorts",
    "Shivajinagar call girl",
    "Shivajinagar escort service",
    "FC Road call girl",
    "FC Road escorts",
    "JM Road call girl",
    "JM Road escorts",
    "Deccan call girl",
    "Deccan Gymkhana escorts",
    "Senapati Bapat Road call girl",
    "SB Road escorts",
    "Kothrud call girl",
    "Kothrud escorts",
    "Kothrud escort service",
    "Paud Road call girl",
    "Karve Road call girl",
    "Warje call girl",
    "Warje escort service",
    "Karve Nagar call girl",
    "Pune Camp call girl",
    "Pune Camp escorts",
    "MG Road call girl pune",
    "East Street call girl pune",
    "Bund Garden call girl",
    "Bund Garden escorts",
    "Satara Road call girl pune",
    "Katraj call girl",
    "Katraj escorts",
    "Katraj escort service",
    "Bharati Vidyapeeth call girl",
    "Kondhwa call girl",
    "Kondhwa escorts",
    "Kondhwa escort service",
    "NIBM Road call girl",
    "NIBM escorts",
    "Wanowrie call girl",
    "Wanowrie escorts",
    "Fatima Nagar call girl",
    "Bibwewadi call girl",
    "Bibwewadi escorts",
    "Sahakar Nagar call girl",
    "Dhankawadi call girl",
    "Ambegaon call girl",
    "Sinhagad Road call girl",
    "Sinhagad Road escorts",

    // Intent, Booking & Quality Search Phrases
    "hotel outcall escorts Pune",
    "incall escort service Pune",
    "24/7 call girl service Pune",
    "24 hour escort service Pune",
    "genuine call girl in Pune",
    "verified Pune escorts",
    "verified call girls Pune",
    "cheap call girls in Pune",
    "affordable escorts Pune",
    "luxury escorts in Pune",
    "high profile escorts Pune",
    "VIP call girl service Pune",
    "cash on delivery call girl Pune",
    "zero advance call girl Pune",
    "WhatsApp call girl number Pune",
    "Pune call girl WhatsApp contact",
    "Pune companion service",
    "best escort service Pune",
    "top rated escorts in Pune",
    "night stay escort service Pune",
    "dinner date escorts Pune",
  ],
  creator: "Anjali Escort Service",
  publisher: "Anjali Escort Service",
  icons: {
    icon: [{ url: "/icon.png", type: "image/png" }],
    shortcut: ["/icon.png"],
    apple: [{ url: "/icon.png", type: "image/png" }],
  },
  metadataBase: new URL(siteUrl),
  alternates: {
    canonical: siteUrl,
  },
  openGraph: {
    title: "Anjali Escort Service | Premium Escorts in Pune & PCMC",
    description: "Anjali Escort Service provides professional, elegant, and discreet escort services in Pune. Explore verified profiles and contact us 24/7.",
    url: siteUrl,
    siteName: "Anjali Escort Service",
    locale: "en_IN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Anjali Escort Service | Premium Escorts in Pune & PCMC",
    description: "Anjali Escort Service provides professional, elegant, and discreet escort services in Pune. Explore verified profiles and contact us 24/7.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": `${siteUrl}/#website`,
      "url": siteUrl,
      "name": "Anjali Escort Service",
      "alternateName": ["CalGirl Anjali", "Anjali Pune Escorts", "Call Girl Pune"],
      "description": "Premier Escort Service and Call Girls in Pune & PCMC. 100% verified independent companions available 24/7.",
      "publisher": {
        "@id": `${siteUrl}/#organization`,
      },
      "inLanguage": "en-IN",
      "potentialAction": {
        "@type": "SearchAction",
        "target": {
          "@type": "EntryPoint",
          "urlTemplate": `${siteUrl}/product?city={search_term_string}`,
        },
        "query-input": "required name=search_term_string",
      },
    },
    {
      "@type": "LocalBusiness",
      "@id": `${siteUrl}/#organization`,
      "name": "Anjali Escort Service",
      "alternateName": "CalGirl Anjali",
      "url": siteUrl,
      "logo": `${siteUrl}/images/logo.png`,
      "image": `${siteUrl}/images/firstpage.avif`,
      "description": "Verified VIP Call Girls & Escort Service in Pune, PCMC, Hinjewadi, Pune Bus Stand & Railway Station with direct WhatsApp and phone booking.",
      "telephone": "+91-8294107610",
      "priceRange": "₹₹₹",
      "currenciesAccepted": "INR",
      "paymentAccepted": "Cash, UPI, Online",
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "Koregaon Park / Hinjewadi / Viman Nagar / PCMC",
        "addressLocality": "Pune",
        "addressRegion": "Maharashtra",
        "postalCode": "411001",
        "addressCountry": "IN",
      },
      "geo": {
        "@type": "GeoCoordinates",
        "latitude": 18.5204,
        "longitude": 73.8567,
      },
      "openingHoursSpecification": [
        {
          "@type": "OpeningHoursSpecification",
          "dayOfWeek": [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday",
            "Sunday",
          ],
          "opens": "00:00",
          "closes": "23:59",
        },
      ],
      "areaServed": [
        "Pune",
        "PCMC",
        "Pimpri Chinchwad",
        "Hinjewadi",
        "Hinjewadi Phase 1",
        "Hinjewadi Phase 2",
        "Hinjewadi Phase 3",
        "Pune Railway Station",
        "Pune Bus Stand",
        "Swargate",
        "Swargate Bus Stand",
        "Koregaon Park",
        "Kalyani Nagar",
        "Viman Nagar",
        "Baner",
        "Baner High Street",
        "Wakad",
        "Kothrud",
        "Shivajinagar",
        "Aundh",
        "Magarpatta City",
        "Kharadi",
        "Hadapsar",
        "Pimple Saudagar",
        "Pimple Nilakh",
        "Bhosari",
        "Chakan",
        "Nigdi",
        "Akurdi",
        "Katraj",
        "Bavdhan",
        "Pune Camp",
        "Yerwada",
        "Wagholi",
        "Balewadi",
        "Pashan",
        "Chandani Chowk",
        "Deccan Gymkhana",
        "FC Road",
        "JM Road",
        "Kondhwa",
        "NIBM Road",
        "Wanowrie",
      ],
      "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "4.9",
        "reviewCount": "1480",
        "bestRating": "5",
        "worstRating": "1",
      },
      "contactPoint": {
        "@type": "ContactPoint",
        "telephone": "+91-8294107610",
        "contactType": "customer service",
        "areaServed": "IN",
        "availableLanguage": ["English", "Hindi", "Marathi"],
      },
    },
    {
      "@type": "FAQPage",
      "@id": `${siteUrl}/#faq`,
      "mainEntity": [
        {
          "@type": "Question",
          "name": "How can I book a verified call girl in Pune via Anjali Escort Service?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Booking is instant and 100% confidential. Browse our verified models gallery on calgirlanjali, select your preferred companion, and click the WhatsApp or Call button (+91 82941 07610) to confirm your booking within minutes.",
          },
        },
        {
          "@type": "Question",
          "name": "Which areas in Pune do you provide escort services?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "We provide 24/7 in-call and out-call escort services across all prime locations in Pune and PCMC including Koregaon Park, Kalyani Nagar, Viman Nagar, Hinjewadi IT Park, Baner, Wakad, Kothrud, Magarpatta City, Kharadi, and Shivaji Nagar.",
          },
        },
        {
          "@type": "Question",
          "name": "Are the escort photos and profiles 100% genuine and verified?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Yes, every companion profile on Anjali Escort Service is verified with genuine recent photos, accurate specifications, and real direct contact information.",
          },
        },
        {
          "@type": "Question",
          "name": "Is my privacy and confidentiality guaranteed?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Absolutely. We maintain strict discretion and client privacy. No personal data is shared or retained.",
          },
        },
      ],
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="min-h-full flex flex-col justify-between bg-white text-zinc-800 font-sans">
        <HeaderPage />
        <main className="flex-1">{children}</main>
        <FooterPage />
      </body>
    </html>
  );
}
